config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_up: ENV['SIGN_UP']}

  resources :blogs
  resources :categories, only: [:show]

  get 'detailed_profile' => 'blogs#detailed_profile'
  root 'blogs#index'
  get 'search' => 'blogs#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	attachment :image
	validates :title, :body, :image, presence: true
	belongs_to :category
	is_impressionable counter_cache: true

	def self.search(search)
      if search
        Blog.where(['body LIKE ? OR title LIKE ?', "%#{search}%", "%#{search}%"])
      else
        Blog.all
      end
    end
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :blogs, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	impressionist :actions=> [:show]

  def new
    if user_signed_in?
  	@blog = Blog.new
  else
    redirect_to blogs_path
  end
  end

  def create
  	@blog = Blog.new(blog_params)
  if @blog.save
	redirect_to blog_path(@blog)
  else
  	render :new
  end
  end

  def show
  	@blog = Blog.find(params[:id])
  	impressionist(@blog, nil, unique: [:session_hash])
  	@blog.save
  end

  def edit
    if user_signed_in?
  	@blog = Blog.find(params[:id])
  else
    redirect_to blogs_path
  end
  end

  def update
  	@blog = Blog.find(params[:id])
  if @blog.update(blog_params)
  	redirect_to blog_path(@blog)
 else
 	render :edit
 end
  end

  def destroy
    if user_signed_in?
  	blog = Blog.find(params[:id])
  	blog.destroy
  	redirect_to blogs_path
  else
    redirect_to blogs_path
  end
  end

  def index
  	@blogs = Blog.page(params[:page]).reverse_order
  end

  def search
  	@search = Blog.search(params[:search]).page(params[:page]).reverse_order
  end

  def detailed_profile
  end


  private

  def blog_params
  	params.require(:blog).permit(:title, :category_id, :body, :image)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def show
		@category = Category.find(params[:id]).name
		@blog = Blog.where(category_id: params[:id]).page(params[:page]).reverse_order
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/blogs/_list_bottom.html.erb
<div class="side-bar">
				<section class="profile-box">
					<h2 class="profile-headline">Profile</h2>
					<div class="profile-line"></div>
					<div class="profile-img-box"></div>
					<h3 class="profile-name">シュンスケ</h3>
					<div class="name-line"></div>
					<p class="profile-detail">sample-textsample-textsample-text<br>
					sample-textsample-textsample-textsample-textsample-textsample-textsample-textsample-textsample-textsample-textsample-textsample-textsample-textsample-textsample-textsample-text</p>
					<p class="profile-detail">sample-textsample-textsample-textsample-textsample-textsample-textsample-textsample-textsample-textsample-textsample-text</p>

					<p class="profile-link-text"><a class="profile-link" href="/detailed_profile">Detailed profile...</a></p>
				</section>

				<div class="searching-box">
					<%= form_tag(search_path, :method => 'get') do %>
 						 <%= text_field_tag :search, "", class: "searching-box-content", placeholder: "   searching..." %>
  							<%= button_tag type: 'submit', :name => nil, class: "btn btn-primary" do %>
  							<i class="fas fa-search"></i>
  							<% end %>
								<% end %>
				</div>
				<% blog = Blog.order('impressions_count DESC').take(3) %>

				<section class="popular-box">
					<h2 class="popular-headline">Popular</h2>
					<div class="popular-line"></div>
					<% blog.each do |blog| %>
					<div class="popular-contents">
						<div class="popular-img">
							<span class="category"><%= link_to blog.category.name, category_path(blog.category_id), class: "category-link" %></span>
							<%=link_to attachment_image_tag(blog, :image, class: "popular-img", format: 'jpeg'), blog_path(blog) %>
						</div>
						<p class="popular-text"><%= blog.title %></p>
						<%= link_to "read more...", blog_path(blog), class: "blog-read-more" %>
					</div>
					<% end %>
				</section>
			</div>
		</div>
	</main>

		<section class="main2 clearfix">
			<div class="main2-box">
				<h1 class="main2-text">Contact</h1>
				<div class="Contact-line"></div>
				<p class="Contact-text-1">↓お仕事のご依頼はこちらから↓</p>
				<p class="Contact-text-2">Mail<a class="contact-link" href="mailto:@gmail.com"> google@gmail.com</a><br>
					TELL<a class="contact-link" href="tel:090-0000-0000"> 090-0000-0000</a></p>
			</div>
			<div class="main2-box">
				<h1 class="main2-text">My product</h1>
				<div class="My-product-line"></div>
				<p class="My-product-text1">
					これまでに作ってきたWebサービスです。<br>
					↓ご愛用いただければ幸いです(^ ^)↓
				</p>
				<p class="My-product-text2">
					<a class="product-link" href="/blogs">>>product1</a><br>
					<a class="product-link" href="/blogs">>>product2</a><br>
					<a class="product-link" href="/blogs">>>product3</a>
				</p>
			</div>
			<div class="main2-box">
				<h1 class="main2-text">SNS</h1>
				<div class="SNS-line"></div>
				<p class="SNS-text-1">
					毎日良質な情報を発信しています。<br>
					↓気軽にフォローしてください＾＾↓
				</p>
					<a class="icon-main2-SNS fab fa-twitter-square" href="https://twitter.com/s_yngy" target="_blank" style="color: #359aff;"></a>
					<a class="icon-main2-SNS fas fa-rss-square" href="/blogs" style="color: #9df934;"></a>
					<a class="icon-main2-SNS fab fa-facebook-square" href="/blogs" style="color: #3670f7;"></a>
			</div>
		</section>
	<footer>
		<p class="footer-text">©︎-Shunsuke Yanagiya 2019 All Rights Reserved.<%=link_to ' path', new_user_session_path, class: "footer-link" %> and <%=link_to ' out.', destroy_user_session_path, method: :delete, class: "footer-link" %>
			<% if user_signed_in? %>
			<%= link_to "new", new_blog_path, class: "footer-link" %>
			<% end %>
		</p>
	</footer>
</body>

</html>

app/views/blogs/_list_top.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
	<title>shunblog</title>
</head>

<body>
	<header>
		<div class="header-top">
			<a class="link-top" href="/blogs"><%= image_tag 'img/shunblog.png', class: 'shunblog'%></a>
			    <p class="header-name">Written by Shunsuke Yanagiya</p>
		</div>
	</header>
	<header class="response-header clearfix">
		<a href="/blogs"><h1 class="blog-name">shunblog</h1></a>

	</header>
	<nav class="normal-nav">
		<ul class="nav-list">
			<li class="nav-list-item"><a class="icon-nav icon-top fas fa-book-open" href="/blogs"> All articles</a></li>
			<li class="nav-list-item", ><%= link_to ' Programming', category_path(1), class: "icon-nav fas fa-code" %> </li>
			<li class="nav-list-item"><%= link_to ' Investment', category_path(2), class: "icon-nav fas fa-chart-line" %></li>
			<li class="nav-list-item"><%= link_to ' Self-help', category_path(3), class: "icon-nav fas fa-running" %></li>
			<li class="nav-list-item"><%= link_to ' Side-job', category_path(4), class: "icon-nav fas fa-dollar-sign" %></li>
		</ul>
	</nav>

	<nav class="respond-nav">
		<ul class="nav-list">
			<li class="nav-list-item"><a class="icon-nav icon-top fas fa-book-open" href="/blogs"> All</a></li>
			<li class="nav-list-item"><%= link_to ' Program', category_path(1), class: "icon-nav fas fa-code" %> </li>
			<li class="nav-list-item"><%= link_to ' Invest', category_path(2), class: "icon-nav fas fa-chart-line" %></li>
			<li class="nav-list-item"><%= link_to ' Self-help', category_path(3), class: "icon-nav fas fa-running" %></li>
			<li class="nav-list-item"><%= link_to ' Side-job', category_path(4), class: "icon-nav fas fa-dollar-sign" %></li>
		</ul>
	</nav>

	<section class="main-visual">
		<div class="main-visual-contents">
			<h1 class="main-visual-text">Thanks for coming!</h1>
			<p class="main-visual-text-2">プログラミング、投資、マインドセット、副業などの<br>
			良質なコンテンツをお届けいたします。</p>
		</div>
	</section>

	<main class="main-media">
		<div class="main-contents clearfix">

app/views/blogs/detailed_profile.html.erb
<%= render 'blogs/list_top' %>
			<section class="Blog">
				<h2 class="blog-headline">Detailed profile</h2>
				<div class="blog-profile-line"></div>
				<div class="blog-contents clearfix">
				  <div class="main-profile-img"></div>
				  <div class="main-SNS-box">
					 <h1 class="main-profile-SNS">SNS</h1>
				  <div class="SNS-line"></div>
				  <p class="SNS-text-1">
					 毎日良質な情報を発信しています。<br>
					 ↓気軽にフォローしてください＾＾↓
				  </p>
					<a class="icon-main2-SNS fab fa-twitter-square" href="https://twitter.com/s_yngy" target="_blank" style="color: #359aff;"></a>
					<a class="icon-main2-SNS fas fa-rss-square" href="/detailed_profile" style="color: #9df934;"></a>
					<a class="icon-main2-SNS fab fa-facebook-square" href="/detailed_profile" style="color: #3670f7;"></a>
				  </div>
				</div>
				<div class="main-profile-text-contents">
					<h2 class="Self-introduction">Self-introduction</h2>
					<div class="Self-introduction-line"></div>
				  <p class="main-profile-text">
				  	sample-textsample-textsample-text<br>
					sample-textsample-textsample-textsample-textsample-textsample-textsample-textsample-text<br>sample-textsample-textsample-textsample-textsample-textsample-textsample-textsample-textsample-textsample-textsample-text</p>
				 <p class="main-profile-text">
					sample-textsample-text<br>sample-textsample-textsample-textsample-textsample-textsample-text<br>sample-textsample-textsample-textsample-textsample-textsample-textsample-textsample-textsample-textsample-textsample-text</p>
				 <p class="main-profile-text">
					sample-textsample-text<br>sample-textsample-textsample-textsample-textsample-textsample-text<br>sample-textsample-textsample-textsample-textsample-textsample-textsample-textsample-text
				 </p>
				</div>
				<div class="myskills-box">
					<h2 class="myskills">My skills</h2>
					<div class="myskills-line"></div>
					<p class="myskills-text">
						sample-textsample-textsample-textsample-textsample-text<br>
						sample-textsample-textsample-textsample-textsample-text
					</p>
					<p class="myskills-text">
						sample-textsample-textsample-textsample-textsample-text<br>
						sample-textsample-textsample-textsample-textsample-text
					</p>
					<p class="myskills-text">
						sample-textsample-textsample-textsample-textsample-text<br>
						sample-textsample-textsample-textsample-textsample-text
					</p>
				</div>
				<div class="schedule-box">
					<h2 class="schedule">Schedule</h2>
					<div class="schedule-line"></div>
					<p class="schedule-text">
						sample-textsample-textsample-textsample-textsample-text<br>
						sample-textsample-textsample-textsample-textsample-text
					</p>
					<p class="schedule-text">
						sample-textsample-textsample-textsample-textsample-text<br>
						sample-textsample-textsample-textsample-textsample-text
					</p>
					<p class="schedule-text">
						sample-textsample-textsample-textsample-textsample-text<br>
						sample-textsample-textsample-textsample-textsample-text
					</p>
				</div>
			</section>

<%= render 'blogs/list_bottom' %>

app/views/blogs/edit.html.erb
<div class="form-box">
<h1>shunblog editing</h1>

<%= form_for(@blog) do |f| %>

<% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %> error has occurred.</h2>
      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <h3 class="form-box-h3">title</h3>
    <%= f.text_field :title, :size => "30", :style => "font-size: 15px;" %>

    <h3 class="form-box-h3">category</h3>
    <%= f.select :category_id, {'Programming' => 1, 'Investment' => 2, 'Self-help' => 3, 'Side-job' => 4 }, {}, { style: " font-size: 15px;"} %>

    <h3 class="form-box-h3">image</h3>
    <%= f.attachment_field :image %>

    <h3 class="form-box-h3">body</h3>
    <%= f.text_area :body, :size => "40x20", style: "font-size: 15px;" %>
    <div></div>
    <input type="submit" value="Post" class="button" onclick=' confirm("Are you sure?")'>

<% end %>

<%= link_to "Back", blog_path(@blog), class: "back-link" %>

</div>

app/views/blogs/index.html.erb
<%= render 'blogs/list_top' %>

			<section class="Blog clearfix">
				<h2 class="blog-headline">All articles</h2>
				<div class="blog-line"></div>

				<% @blogs.each do |blog| %>
				<div class="blog-box">
					<div class="blog-img">
						<span class="category"><%= link_to blog.category.name, category_path(blog.category_id), class: "category-link" %></span>
						<%= link_to blog_path(blog) do %>
						<%= attachment_image_tag(blog, :image, class: "blog-image", format: 'jpeg') %>
						<% end %>
					</div>
					<h2 class="blog-text"><%= blog.title %></h2>
					<%= link_to "read more...", blog_path(blog), class: "blog-read-more" %>
				</div>
				<% end %>
				<%= paginate @blogs, class: "paginate" %>
			</section>

<%= render 'blogs/list_bottom' %>

app/views/blogs/new.html.erb
<div class="form-box">
<h1>shunblog new posts</h1>

<%= form_for(@blog) do |f| %>

<% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %> error has occurred.</h2>
      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <h3 class="form-box-h3">title</h3>
    <%= f.text_field :title, :size => "30", :style => "font-size: 15px;" %>

    <h3 class="form-box-h3">category</h3>
    <%= f.select :category_id, {'Programming' => 1, 'Investment' => 2, 'Self-help' => 3, 'Side-job' => 4 }, {}, { style: " font-size: 15px;"} %>

    <h3 class="form-box-h3">image</h3>
    <%= f.attachment_field :image %>

    <h3 class="form-box-h3">body</h3>
    <%= f.text_area :body, :size => "40x20", style: "font-size: 15px;" %>
    <div></div>
    <input type="submit" value="Post" class="button" onclick=' confirm("Are you sure?")'>

<% end %>

<%= link_to "Back", blogs_path, class: "back-link" %>

</div>

app/views/blogs/search.html.erb
<%= render 'blogs/list_top' %>

			<section class="Blog clearfix">
				<h2 class="blog-headline">Search result</h2>
				<div class="blog-line"></div>

				<% @search.each do |blog| %>
				<div class="blog-box">
					<div class="blog-img">
						<span class="category"><%= link_to blog.category.name, category_path(blog.category_id), class: "category-link" %></span>
						<%= attachment_image_tag blog, :image, class: "blog-image", format: 'jpeg' %>
					</div>
					<h2 class="blog-text"><%= blog.title %></h2>
					<%= link_to "read more...", blog_path(blog), class: "blog-read-more" %>
				</div>
				<% end %>
				<%= paginate @search, class: "paginate" %>
			</section>

<%= render 'blogs/list_bottom' %>

app/views/blogs/show.html.erb
<%= render 'blogs/list_top' %>

			<section class="Blog show-blog">
				<p class="created-text">作成日:<%= @blog.created_at.strftime('%Y/%m/%d') %></p>
				<h1 class="blog-title"><%= @blog.title %></h1>
				<%= link_to @blog.category.name, category_path(@blog.category_id), class: "icon-tag fas fa-tags" %>
				<%= attachment_image_tag @blog, :image, class: "blog-show-img", format: 'jpeg' %>

				<p class="blog-show-text"><%= @blog.body %></p>

				<%= link_to @blog.category.name, category_path(@blog.category_id), class: "icon-tag fas fa-tags" %> /
				<% if user_signed_in? %>

				<%= link_to "Edit", edit_blog_path(@blog) %> / <%= link_to "Delete", blog_path(@blog), method: :delete, "data-confirm" => "Are you sure?" %> / 
				<% end %>
				<%= link_to 'All articles', blogs_path %>
				<p class="PV-count">PV <%=  @blog.impressionist_count %></p>
			</section>

<%= render 'blogs/list_bottom' %>

app/views/categories/_list_bottom.html.erb
<div class="side-bar">
				<section class="profile-box">
					<h2 class="profile-headline">Profile</h2>
					<div class="profile-line"></div>
					<div class="profile-img-box"></div>
					<h3 class="profile-name">シュンスケ</h3>
					<div class="name-line"></div>
					<p class="profile-detail">sample-textsample-textsample-text<br>
					sample-textsample-textsample-textsample-textsample-textsample-textsample-textsample-textsample-textsample-textsample-textsample-textsample-textsample-textsample-textsample-text</p>
					<p class="profile-detail">sample-textsample-textsample-textsample-textsample-textsample-textsample-textsample-textsample-textsample-textsample-text</p>

					<p class="profile-link-text"><a class="profile-link" href="/detailed_profile">Detailed profile...</a></p>
				</section>

				<div class="searching-box">
					<%= form_tag(search_path, :method => 'get') do %>
 						 <%= text_field_tag :search, "", class: "searching-box-content", placeholder: "   searching..." %>
  							<%= button_tag type: 'submit', :name => nil, class: "btn btn-primary" do %>
  							<i class="fas fa-search"></i>
  							<% end %>
								<% end %>
				</div>
				<% blog = Blog.order('impressions_count DESC').take(3) %>

				<section class="popular-box">
					<h2 class="popular-headline">Popular</h2>
					<div class="popular-line"></div>
					<% blog.each do |blog| %>
					<div class="popular-contents">
						<div class="popular-img">
							<span class="category"><%= link_to blog.category.name, category_path(blog.category_id), class: "category-link" %></span>
							<%=link_to attachment_image_tag(blog, :image, class: "popular-img", format: 'jpeg'), blog_path(blog) %>
						</div>
						<p class="popular-text"><%= blog.title %></p>
						<%= link_to "read more...", blog_path(blog), class: "blog-read-more" %>
					</div>
					<% end %>
				</section>
			</div>
		</div>
	</main>

		<section class="main2 clearfix">
			<div class="main2-box">
				<h1 class="main2-text">Contact</h1>
				<div class="Contact-line"></div>
				<p class="Contact-text-1">↓お仕事のご依頼はこちらから↓</p>
				<p class="Contact-text-2">Mail<a class="contact-link" href="mailto:@gmail.com"> google@gmail.com</a><br>
					TELL<a class="contact-link" href="tel:090-0000-0000"> 090-0000-0000</a></p>
			</div>
			<div class="main2-box">
				<h1 class="main2-text">My product</h1>
				<div class="My-product-line"></div>
				<p class="My-product-text1">
					これまでに作ってきたWebサービスです。<br>
					↓ご愛用いただければ幸いです(^ ^)↓
				</p>
				<p class="My-product-text2">
					<a class="product-link" href="/blogs">>>product1</a><br>
					<a class="product-link" href="/blogs">>>product2</a><br>
					<a class="product-link" href="/blogs">>>product3</a>
				</p>
			</div>
			<div class="main2-box">
				<h1 class="main2-text">SNS</h1>
				<div class="SNS-line"></div>
				<p class="SNS-text-1">
					毎日良質な情報を発信しています。<br>
					↓気軽にフォローしてください＾＾↓
				</p>
					<a class="icon-main2-SNS fab fa-twitter-square" href="https://twitter.com/s_yngy" target="_blank" style="color: #359aff;"></a>
					<a class="icon-main2-SNS fas fa-rss-square" href="/blogs" style="color: #9df934;"></a>
					<a class="icon-main2-SNS fab fa-facebook-square" href="/blogs" style="color: #3670f7;"></a>
			</div>
		</section>
	<footer>
		<p class="footer-text">©︎-Shunsuke Yanagiya 2019 All Rights Reserved.<%=link_to ' path', new_user_session_path, class: "footer-link" %> and <%=link_to ' out.', destroy_user_session_path, method: :delete, class: "footer-link" %>
			<% if user_signed_in? %>
			<%= link_to "new", new_blog_path, class: "footer-link" %>
			<% end %>
		</p>
	</footer>
</body>

</html>

app/views/categories/_list_top.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
	<title>shunblog</title>
</head>

<body>
	<header>
		<div class="header-top">
			<a class="link-top" href="/blogs"><%= image_tag 'img/shunblog.png', class: 'shunblog'%></a>
			    <p class="header-name">Written by Shunsuke Yanagiya</p>
		</div>
	</header>
	<header class="response-header clearfix">
		<a href="/blogs"><h1 class="blog-name">shunblog</h1></a>

	</header>
	<nav class="normal-nav">
		<ul class="nav-list">
			<li class="nav-list-item"><a class="icon-nav icon-top fas fa-book-open" href="/blogs"> All articles</a></li>
			<li class="nav-list-item"><%= link_to ' Programming', category_path(1), class: "icon-nav fas fa-code" %> </li>
			<li class="nav-list-item"><%= link_to ' Investment', category_path(2), class: "icon-nav fas fa-chart-line" %></li>
			<li class="nav-list-item"><%= link_to ' Self-help', category_path(3), class: "icon-nav fas fa-running" %></li>
			<li class="nav-list-item"><%= link_to ' Side-job', category_path(4), class: "icon-nav fas fa-dollar-sign" %></li>
		</ul>
	</nav>

	<nav class="respond-nav">
		<ul class="nav-list">
			<li class="nav-list-item"><a class="icon-nav icon-top fas fa-book-open" href="/blogs"> All</a></li>
			<li class="nav-list-item"><%= link_to ' Program', category_path(1), class: "icon-nav fas fa-code" %> </li>
			<li class="nav-list-item"><%= link_to ' Invest', category_path(2), class: "icon-nav fas fa-chart-line" %></li>
			<li class="nav-list-item"><%= link_to ' Self-help', category_path(3), class: "icon-nav fas fa-running" %></li>
			<li class="nav-list-item"><%= link_to ' Side-job', category_path(4), class: "icon-nav fas fa-dollar-sign" %></li>
		</ul>
	</nav>

	<section class="main-visual">
		<div class="main-visual-contents">
			<h1 class="main-visual-text">Thanks for coming!</h1>
			<p class="main-visual-text-2">プログラミング、投資、マインドセット、副業などの<br>
			良質なコンテンツをお届けいたします。</p>
		</div>
	</section>

	<main class="main-media">
		<div class="main-contents clearfix">

app/views/categories/show.html.erb
<%= render 'categories/list_top' %>

			<section class="Blog clearfix">
				<h2 class="blog-headline"><%= @category %></h2>

				<div class="blog-line"></div>
				<% @blog.each do |blog| %>
				<div class="blog-box">
					<div class="blog-img">
						<span class="category"><%= link_to blog.category.name, category_path(blog.category_id), class: "category-link" %></span>
						<%= attachment_image_tag blog, :image, class: "blog-image", format: 'jpeg' %>
					</div>
					<h2 class="blog-text"><%= blog.title %></h2>
					<%= link_to "read more...", blog_path(blog), class: "blog-read-more" %>
				</div>
				<% end %>
				<%= paginate @blog, class: "paginate" %>
			</section>

<%= render 'categories/list_bottom' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shunblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'  %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>